### ISSUE TITLE
Double volume key press / power button

### ISSUE THREAD

**Issue by Gordalf** [hufrea/keysh#10]
Hi

First of all thanks for your awesome app. I have been looking for years for something like your app. 

I have two questions. 

- Is it possible to use the power key to turn on/off flashlight?

- If it isn't possible to use the power button - would it then be possible to press volume up and volume down at the same time and turn on/off the flashlight? There is an app which does just that but I am unable to use it since I run Grapheneos https://github.com/anselm94/Torchie-Android/

Also I would like to donate to the project - is that possible?

**Comment by hufrea** [comment]
Hi.
> Is it possible to use the power key

No.

> would it then be possible to press volume up and volume down at the same time and turn on/off the flashlight?

Yes, you can write something like this:
<details><summary>Code</summary>

```sh
set -eu

torch_state="on"

torch_on_off() {
    torch $torch_state
    [ "$torch_state" = "off" ] && torch_state="on" ||
        torch_state="off"
}

on_down() {
    read key 
    [ "$key" = "$RELEASE_DOWN" ] && {
        volume current down
        return
    }
    torch_on_off
    
}

on_up() {
    read key 
    [ "$key" = "$RELEASE_UP" ] && {
        volume current up
        return
    }
    torch_on_off
}

loop() {
    while read key; do
        wakelock acquire 5000
        
        case "$key" in
            "$PRESS_UP" )
                on_up
            ;;
            "$PRESS_DOWN" )
                on_down
            ;;
        esac
        wakelock release
    done
}

###

vibrate() {
    # <duration_ms>
    echo "vibrate $*";
}
wakelock() {
    # acquire|release [timeout_ms]
    echo "wakelock $*";
}
volume() {
    # music|notification|ring|call up|down|<level>
    echo "volume $*";
}
torch() {
    # on|off
    echo "torch $*";
}

loop
```

</details>

**Comment by Gordalf** [comment]
Cool. That code works as intended. Last thing i promise. How do i incorporate the torch code with media controls?

Below is the code I want to use:

<details><summary>Code</summary>
<p>

set -eu

# Up 300ms  -> next track
# Down 30ms -> prev track

TO=0.300
DUR_S=25
WL_MAX=1500


on_up() {
    read -t $TO key && {
        volume music up
        return
    }
    media next
    vibrate $DUR_S
}


on_down() {
    read -t $TO key && {
        volume music down
        return
    }
    media play_pause
    vibrate $DUR_S
}


loop() {
  while read key; do
    wakelock acquire $WL_MAX
      case "$key" in
          "$PRESS_UP" )
              on_up
          ;;
          "$PRESS_DOWN" )
              on_down
          ;;
      esac
      wakelock release
  done
}


### Supported commands

DELIM="|+|"

vibrate() {
    # <duration_ms>
    echo "vibrate $*";
}
wakelock() {
    # acquire|release [timeout_ms]
    echo "wakelock $*";
}
media() {
    # play_pause|next|previous|rewind|forward|stop
    echo "media $*";
}
volume() {
    # music|notification|ring|call|current up|down|<level>
    echo "volume $*";
}
torch() {
    # on|off
    echo "torch $*";
}
notify() {
    # -c <content> -t <title>
    # -i <id> -l <timeout_ms>
    ARGS=""
    for arg in "$@"; do
        ARGS="${ARGS}${DELIM}${arg}"
    done
    echo ":${DELIM}:notify${ARGS}";
}
intent() {
    # -a <action>
    # -t service|broadcast|activity
    # -p <package/.Component>
    # -d <data> -m <mimetype> -c <category>
    # -e <extra_key>:<extra_value>
    # -e <extra_key>:{:<delimiter>:<ex_val1><delimiter><ex_val2>}
    ARGS=""
    for arg in "$@"; do
        ARGS="${ARGS}${DELIM}${arg}"
    done
    echo ":${DELIM}:intent${ARGS}";
}
permission() {
    # BACKGROUND_ACTIVITY
    # STORAGE|TERMUX_RUN_COMMAND
    echo "permission $*";
}


loop


</p>
</details>

**Comment by hufrea** [comment]
<details><summary>Code</summary>

```sh
set -eu

TO=0.300
torch_state="on"

torch_on_off() {
    torch $torch_state
    [ "$torch_state" = "off" ] && torch_state="on" ||
        torch_state="off"
}

on_down() {
    read -t $TO key || {
        media previous
        return
    }
    case $key in
        "$RELEASE_DOWN")
            volume current down ;;
         *)
             torch_on_off ;;
    esac
}

on_up() {
    read -t $TO key || {
        media next
        return
    }
    case $key in
        "$RELEASE_UP")
            volume current up ;;
         *)
             torch_on_off ;;
    esac
}

loop() {
    while read key; do
        wakelock acquire 5000
        
        case "$key" in
            "$PRESS_UP" )
                on_up
            ;;
            "$PRESS_DOWN" )
                on_down
            ;;
        esac
        wakelock release
    done
}

###

media() {
    echo "media $@"
}
vibrate() {
    echo "vibrate $*";
}
wakelock() {
    echo "wakelock $*";
}
volume() {
    echo "volume $*";
}
torch() {
    echo "torch $*";
}

loop
```
</details>

**Comment by Gordalf** [comment]
Thanks a lot. I will recommend your app to everyone i know might be interested
