### ISSUE TITLE
Volume Button to wake up the device

### ISSUE THREAD

**Issue by sathya731** [hufrea/keysh#12]
Hi, My power button is busted. So, when the device is on sleep i want any power button to wake the device and when device is on it should function as normal volume control. I am guessing we need root for this since another app i used previously requires root. 
1) Can we achive this usecase without root access?
2) if i give root access to this app from kernelsu. Will it use it?
3) termux already have root access. Can we use termux to wake the device?

Thanks for this awesome app.

**Comment by hufrea** [comment]
With root:
<details>

```sh
while read key; do
    if [ "$key" == "$PRESS_UP" ] ||
            [ "$key" == "$PRESS_DOWN" ]; then
        su -c input keyevent 26
    fi
done
```
</details>

This could also be done without root, but this functionality has not yet been implemented.
