### ISSUE TITLE
Passing shutter function to camera app

### ISSUE THREAD

**Issue by underscoregeb** [hufrea/keysh#16]
My device's camera app supports the use of the volume keys as a shutter button. Is there a way to retain this functionality under Keysh?

I imagine this would mean detecting if the camera app is currently open, and then passing the raw key event, but I'm not sure how to go about that. Is this possible without root?

**Comment by hufrea** [comment]
> Is there a way to retain this functionality under Keysh?

This is possible since 0.1.8, [here is an example](https://github.com/hufrea/keysh/blob/master/examples/exclude_apps.sh)

**Comment by underscoregeb** [comment]
Awesome, thank you!
