### ISSUE TITLE
FR: Network access

### ISSUE THREAD

**Issue by StevenAlexander44** [hufrea/keysh#2]
I see that I can run commands in termux (and that is working very well), but it would be useful if keysh could use curl directly so that I could let a friend install it and paste my script without having to install termux too. As far as I can tell, the only issue with that is the network is locked down (for security?)

Thank you for this app, it's so much nicer than key mapper, especially now that I can actually use arguments with termux!

**Comment by hufrea** [comment]
I added permission, it will be available for the next release. Thanks for your feedback!
