### ISSUE TITLE
Can't change volume on call without a dedicated pattern?

### ISSUE THREAD

**Issue by StevenAlexander44** [hufrea/keysh#3]
Is there a way to let the volume buttons do their default behavior (change call volume on call, media otherwise) without making one pattern for media and another for calling? As a temporary fix, I'm using down for media and up for calling, but I don't think that is a good long-term solution.

Thank you for any assistance!

**Comment by hufrea** [comment]
You can use `volume current`

**Comment by StevenAlexander44** [comment]
Works great! Thank you :)
