### ISSUE TITLE
return the default buttons

### ISSUE THREAD

**Issue by vasilyvaganov** [hufrea/keysh#6]
In special functions, there is an option to enable "keysh" and "background". If you turn on "keysh", then keysh will work even when the screen is on (which is what I need). How can I make sure that when pressing the "down" button, the sound decreases depending on the button being pressed, as is done by default on phones? I tried to do it through "$PRESS_DOWN" and "$RELEASE_DOWN" with a cyclic function, but "$RELEASE_DOWN" does not want to work for me, for some reason...

**Comment by hufrea** [comment]
Do you want to decrease volume while button is held? (или я неправильно понял)

**Comment by vasilyvaganov** [comment]
Да, верно 😅
Пытался сделать так: при нажатии включался цикл volume down, при отжатии кнопки цикл останавливался, но $RELESSE_DOWN не реагирует на отжатие кнопки
Спасибо за приложение, давно подобное искал

**Comment by vasilyvaganov** [comment]
Спасибо, работает! 🖐️
