### ISSUE TITLE
Buttons handling when the screen is on

### ISSUE THREAD

**Issue by ElliotAl86** [hufrea/keysh#7]
Hello! Thank you for such a useful app!
I noticed that the application works only when main activity is visible or when the device's screen is turned off. Is it technically possible to implement a function so that the application also intercepts buttons when the screen is on and other applications are open?

**Comment by hufrea** [comment]
Hello! Yes, and this has already been implemented - go to system settings -> accessibility and enable "Keysh",

**Comment by ElliotAl86** [comment]
It works, thanks! But I would never have thought to look there, maybe it would be nice to add some information about this somewhere. By the way, what is the difference between "Background" and "Keysh"?

<img src='https://github.com/user-attachments/assets/6f06a02c-1c44-44c9-a20c-0116c7196270' width='200'>

**Comment by hufrea** [comment]
"Background" does not handle buttons, it is only needed to increase privileges, for example, to launch activities from the background. I think this implementation still requires improvement, so it is not mentioned anywhere.

**Comment by ElliotAl86** [comment]
Ok, thanks for your help!
