### ISSUE TITLE
Конфликт управления музыкой на часах/браслете

### ISSUE THREAD

**Issue by elifian** [hufrea/keysh#8]
При включенном keysh некорректно ведет себя управление музыкой (увеличение/уменьшение громкости, пауза, старт, следующий/прошлый трек) на mi band 8. Блокирую телефон, на часах может принять 1 любое действие и все, больше не реагирует. Разблокировав телефон, потом заблокировав можно снова выполнить 1 действие и так по кругу. Также заметил закономерность, если долго не пользоваться боковыми кнопками, то для активации keysh, нужно нажать вверх/вниз 1 раз, уже потом только оно принимает команды из sh. Все нужные логи приложу, только сообщите какие

**Comment by vasilyvaganov** [comment]
Добавлю, переключение треков работает, пауза тоже, старт нет, увеличение/уменьшение громкости на отрез не хотят работать при запущенном keysh на заблокированном экране. При этом, у меня стоит специальная функция, когда keysh работает и при включенном экране, при включенном экране уменьшение/прибавление громкости на часах работает исправно, как и другие функции, функции keysh на боковых кнопках - тоже.

**Comment by hufrea** [comment]
Дело в том, что информация о изменении громкости используется как запасной метод определения нажатиий клавиш, поэтому громкость восстанавливается, если громкость явно не изменена из shell-скрипта. Но, после последних изменений, этот метод можно будет удалить, поэтому это будет исправлено.

**Comment by vasilyvaganov** [comment]
Здравствуйте, при последнем обновлении 0.14 управление громкостью при включеном в фоне приложением и заблокированном экране вернулось, но кнопки следующая/прошлая песня и остановить/продолжить слушать музыку не восстановили контроль. Если закрыть приложение, то контроль возвращается.
Если требуется, могу записать видео или иные варианты фидбека

**Comment by hufrea** [comment]
Предполагаю, что ваши часы управляют медиа сессией keysh. Правильно ли отображают ваши часы имя текущего трека, когда приложение запущено?

**Comment by vasilyvaganov** [comment]
Да, правильно, часы mi band 8

**Comment by elifian** [comment]
Решено с последующими обновлениями, спасибо!
